#!/bin/bash
if test $(find ~/.cache/repos -mmin +120)
then
    notify-send "cache file to old"
fi 
find $HOME -type d -name .git \
    | sed -e "s|\(^.*/\)\(.*\)\(/\)\(\.git\)|\2 \1\2|" ~/.cache/repos
