#!/bin/bash

pidof polybar && kill $(pidof polybar)
pidof sxhkd && kill $(pidof sxhkd)
pidof picom && kill $(pidof picom)
pidof unclutter && kill $(pidof unclutter)

picom &
unclutter &
sxhkd 2>&1 | tee ~/.local/var/log/sxhkd.log &
polybar bspwmbar 2>&1 | tee ~/.local/var/log/polybar.log &
