#!/bin/sh

dest=${1-$HOME}
subcommand=${2-all}

case "${subcommand}" in
    all)
        scripts/dotfiles "${dest}"
        scripts/wallpapers "${dest}"
        scripts/fonts "${dest}"
        ;;
    dotfiles)
        scripts/dotfiles "${dest}"
        ;;
    wallpapers)
        scripts/wallpapers "${dest}"
        ;;
    fonts)
        scripts/fonts "${dest}"
        ;;
    check)
        scripts/sanity-check "${dest}"
        ;;
    *) echo "Command not available"
        ;;
esac
