#!/usr/bin/env bash

shopt -s nullglob globstar

lines="20"
prompt="Passwords:"
font="mononoki Nerd Font Mono:pixelsize=24:antialias=true:autohint=true"
selected_bg="#D35351"
selected_fg="#151515"
normal_bg="#505050"
normal_fg="#F5F5F5"
menu_select_bg_color="#F3F3F3"


typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
	menu="/usr/local/bin/wofi -d"
	xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
	menu=dmenu
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "No clipboard or menu software found" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )
echo "${password_files[@]}"
password=$(printf '%s\n' "${password_files[@]}" | \
  $menu  -l ${lines} -fn ${font} -p ${prompt} \
    -sb ${selected_bg} -sf ${selected_fg} \
    -nb ${normal_bg} -nf ${normal_fg})
echo "$password"
[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi
