#!/bin/bash
lines=30
prompt="Repos:"
font="mononoki Nerd Font Mono:pixelsize=24:antialias=true:autohint=true"
selected_bg="#D3E351"
selected_fg="#131313"

normal_fg="#F5F5F5"
normal_bg="#303030"

generate_cache(){
    notify-send "generate cache"
    find $HOME -type d -name .git \
      | sed -e "s|\(^.*/\)\(.*\)\(/\)\(\.git\)|[\2] (\1\2)|" > ~/.cache/repos
}

if ! test -f ~/.cache/repos ;then
    generate_cache
elif test $(find ~/.cache/repos -mmin +60) ;then
    generate_cache
fi

repopath=$(cat ~/.cache/repos | dmenu -l "${lines}" -p "${prompt}" -fn "${font}" \
    -nf "${normal_fg}" -nb "${normal_bg}" \
    -sb "${selected_bg}" -sf "${selected_fg}" | awk '{print $2}')

#notify-send "$result"
notify-send "repo : $repopath"
exec /usr/local/bin/st -e cd ${repopath}
