#!/usr/bin/env bash
lines="20"
prompt="Passwords:"
font="mononoki Nerd Font Mono:pixelsize=24:antialias=true:autohint=true"
selected_bg="#D35351"
selected_fg="#151515"

normal_bg="#505050"
normal_fg="#F5F5F5"

menu_select_bg_color="#F3F3F3"

passmenu -l "${lines}" -fn "${font}" -p "${prompt}" \
    -sb "${selected_bg}" -sf "${selected_fg}" \
    -nb "${normal_bg}" -nf "${normal_fg}"
