#!/bin/bash
lines=30
prompt="Repos ($(wc -l ~/.cache/repos | awk '{print $1}')):"
font="mononoki Nerd Font Mono:pixelsize=24:antialias=true:autohint=true"
selected_bg="#D3E351"
selected_fg="#131313"

normal_fg="#F5F5F5"
normal_bg="#303030"

generate_cache(){
    notify-send "generate cache"
    find $HOME -maxdepth 3 -type d -name .git \
      | sed -e "s|\(^.*/\)\(.*\)\(/\)\(\.git\)|[\2] (\1\2)|" > ~/.cache/repos
}

if ! test -f ~/.cache/repos ;then
    generate_cache
elif test $(find ~/.cache/repos -mmin +60) ;then
    generate_cache
fi

xdotool="xdotool type --clearmodifiers --file -"
cat ~/.cache/repos | dmenu -l "${lines}" -p "${prompt}" -fn "${font}" \
    -nf "${normal_fg}" -nb "${normal_bg}" \
    -sb "${selected_bg}" -sf "${selected_fg}" | { IFS= read -r reponame; printf %s "$reponame"; } | $xdotool
