#!/bin/bash

if [[ -f $HOME/.config/currentlayout.sh ]]; then
  source $HOME/.config/currentlayout.sh
fi

for monitor in $(xrandr --listactivemonitors | grep -v Monitor| awk '{print $4}');do
  bspc monitor $monitor -d 1 2 3 4 5
done

bspc rule -a scratchpad sticky=on state=floating hidden=on rectangle=800x600
[ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && st -c scratchpad -T scratch -e ~/.bin/scratchpad &

bspc config border_width 2
bspc config window_gap   1
bspc config click_to_focus true
bspc config split_ratio 0.52

bspc config active_border_color  \#234393
bspc config focused_border_color \#46E385
bspc config normal_border_color  \#111111

# TODO : systemd user services ?
pidof polybar && kill $(pidof polybar)
pidof sxhkd && kill $(pidof sxhkd)
pidof picom && kill $(pidof picom)
pidof unclutter && kill $(pidof unclutter)

setxkbmap fr &
picom &
unclutter &
sxhkd 2>&1 | tee ~/.local/var/log/sxhkd.log &
polybar bspwmbar 2>&1 | tee ~/.local/var/log/polybar.log &
find ~/wallpapers/ -type f | shuf -n1 | xargs feh --bg-scale
