#!/bin/bash

if [[ -f $HOME/.config/currentlayout.sh ]]; then
  source $HOME/.config/currentlayout.sh
fi

for monitor in $(xrandr --listactivemonitors | grep -v Monitor| awk '{print $4}');do
  bspc monitor $monitor -d 1 2 3 4 5
done

# TODO : Add a trop down terminal like the one i have in i3
# st -name scratchterm &
# bspc rule -a URxvt:scratchterm monitor=DP1 sticky=on state=floating locked=on hidden=on rectangle=1720x720+2780+27

bspc config border_width 2
bspc config window_gap   1
bspc config click_to_focus true
bspc config split_ratio 0.52

bspc config active_border_color  \#234393
bspc config focused_border_color \#46E385
bspc config normal_border_color  \#111111

pidof polybar && kill $(pidof polybar)
pidof sxhkd && kill $(pidof sxhkd)
pidof compton && kill $(pidof compton)
pidof unclutter && kill $(pidof unclutter)

compton &
unclutter &
sxhkd 2>&1 | tee ~/.local/var/log/sxhkd.log &
polybar bspwmbar 2>&1 | tee ~/.local/var/log/polybar.log &
find ~/wallpapers/ -type f | shuf -n1 | xargs feh --bg-scale
