#!/bin/sh

dest="${1}"

[ ! -d "${dest}" ] && mkdir "${dest}"
find src -mindepth 1 -type d -print \
  | sed "s|src/\(.*\)|$dest/.\1|g" | xargs -l mkdir -vp

echo "Install dotfiles"
find src -mindepth 1 -type f -print \
  | sed "s|src/\(.*\)|${PWD}/src/\1 ${dest}/.\1|g" | xargs -l ln -vsf

echo "Install markdown files"
find files -mindepth 1 -type f -print \
  | sed "s|files/\(.*\)|${PWD}/files/\1 ${dest}/\1|g" | xargs -l ln -vsf


if [ ! -f "$HOME/.config/private.bash" ]; then
cat > "$HOME/.config/private.bash" <<EOF
export SOURCECONFIG="$(pwd)"
EOF
fi

exit 0
