#!/bin/bash

font=${2-Mononoki}
echo "Install fonts $font"

find software/nerd-fonts/patched-fonts/$font/ -name "*.ttf" \
    -printf "%p~/.local/share/fonts/%f\n" | sed 's/ /\\ /g' \
    | awk -F~ '{print "cp " $1  " ~" $2}'
 
exit 0
