#!/bin/bash

echo "Install wallpapers"

[ ! -d "$1/wallpapers" ] && mkdir -p $1/wallpapers

wallpaper=(
"https://w.wallhaven.cc/full/m3/wallhaven-m3zjx1.jpg" "$1/wallpapers/tree-01.jpg"
"https://w.wallhaven.cc/full/y8/wallhaven-y8ox8k.jpg" "$1/wallpapers/heart-01.jpg"
"https://w.wallhaven.cc/full/4y/wallhaven-4yzkkn.jpg" "$1/wallpapers/scpace-01.jpg"
"https://w.wallhaven.cc/full/md/wallhaven-mdzl6k.jpg" "$1/wallpapers/nova-01.jpg"
"https://w.wallhaven.cc/full/x1/wallhaven-x1d5zv.png" "$1/wallpapers/steam-01.jpg"
"https://w.wallhaven.cc/full/4o/wallhaven-4oqrwm.png" "$1/wallpapers/program-01.jpg"
"https://w.wallhaven.cc/full/72/wallhaven-72kjz9.jpg" "$1/wallpapers/tree-02.jpg"
)

for (( i=0 ;i<${#wallpaper[*]} ;i=i+2 )) ; do
    [ ! -f ${wallpaper[$i+1]} ] \
      && printf "fetch %-15s : %s\n" $(basename ${wallpaper[$i+1]}) ${wallpaper[$i]} \
      && curl --silent -fLo ${wallpaper[$i+1]} --create-dirs ${wallpaper[$i]}
done

exit 0
