#!/bin/bash

echo "Install wallpapers"

[ ! -d $1/wallpapers ] && echo "mkdir $1/wallpapers" && mkdir $1/wallpapers
wallpaper=(
"https://images8.alphacoders.com/912/912945.jpg" "$1/wallpapers/flying_city.jpg"
"https://images3.alphacoders.com/236/236077.jpg" "$1/wallpapers/gooddesk.jpg"
"https://images4.alphacoders.com/199/199576.jpg" "$1/wallpapers/time.jpg"
"https://images7.alphacoders.com/852/852656.jpg" "$1/wallpapers/landscape.jpg"
"https://images.alphacoders.com/190/190593.jpg"  "$1/wallpapers/clock2.jpg"
"https://images.alphacoders.com/103/103011.jpg"  "$1/wallpapers/blueprint1.jpg"
)
for (( i=0 ;i<${#wallpaper[*]} ;i=i+2 )) ; do
    [ ! -f ${wallpaper[$i+1]} ] \
      && printf "fetch %-15s : %s\n" $(basename ${wallpaper[$i+1]}) ${wallpaper[$i]} \
      && curl --silent -fLo ${wallpaper[$i+1]} --create-dirs ${wallpaper[$i]}
done
exit 0
