#
# ~/.bash_profile
#
SSH_ENV="$HOME/.ssh/agent-environment"

export GPG_TTY=$(tty)
export GPG_AGENT_INFO=`gpgconf --list-dirs agent-socket | tr -d '\n' && echo -n ::`
#eval $(gpg-agent --daemon)

function start_agent() {
  if [[ -z "$(pidof ssh-agent)" || ! -f "${SSH_ENV}" ]];then
    ssh-agent | sed 's/^echo/#echo/'> ${SSH_ENV}
  fi
}
start_agent

[[ -f ~/.bashrc ]] && . ~/.bashrc

#[[ -z $WAYLAND_DISPLAY && $(tty) == "/dev/tty1" ]] && systemctl start sway --user
#sway
