#
# ~/.bash_profile
#
SSH_ENV="$HOME/.ssh/agent-environment"
function start_agent() {
  if [[ -z "$(pidof ssh-agent)" || ! -f "${SSH_ENV}" ]];then
    ssh-agent | sed 's/^echo/#echo/'> ${SSH_ENV}
  fi
}

start_agent

[[ -f ~/.bashrc ]] && . ~/.bashrc
[[ -z $DISPLAY && $(tty) == "/dev/tty1" ]] && startx || true
